### ISSUE TITLE
Blogs sometimes do not change their color after their downloads have completed

### ISSUE THREAD

**Issue by ErikBrown2** [TumblThreeApp/TumblThree#149]
**Describe the bug**
When you have queued multiple blogs for crawling and start the crawling, then the active blog will be highlighted in green in the blog list and in blue in the queue list. When the blog has finished the crawling, then the green highlight will be reset for that blog to the normal color and the blog will disappear from the queue. But this resetting of the green color and removal of the blog from the queue does not always happen. So blogs stay highlighted in green and in blue on the queue list even though crawling them had finished.
**To Reproduce**
1. Go to '...'TumblThree, queue a few blogs and click on Crawl.
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
I would expect that the green highlight of the blog will always be removed for that blog when the crawling finished for that blog. And also that the blog will always be removed from the queue when crawling has finished.
**Screenshots*
<img width="185" alt="Screenshot 2021-05-17 200401" src="https://user-images.githubusercontent.com/32511867/118520359-10f73a00-b74b-11eb-9b43-a51fc8d50fda.png">
*
I have added a screenshot of the queue that shows multiple queued blogs still in the queue while their crawling had finished.
**Desktop (please complete the following information):**
 - TumblThree version: [e.g. 1.0.11.3] 1.5.1.145 but also several earlier versions
 - OS: [e.g. Windows 10 Home] Windows 10 Pro
 - Browser [e.g. Chrome, Safari, IE, Edge] Chrome 
 - Version [e.g. 22] Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**

**Comment by thomas694** [comment]
Hi Erik,
thanks for reporting this bug. What value for "concurrent blogs" are you using? It looks like 1, but maybe one already hung.
Can you also check the TumblThree log file for an error after a crawler finished, meaning the moment the number of blue items in the queue list gets one more resp. another green line appears in the blog list?

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by ErikBrown2** [comment]
Also in this version is it not solved,. See the screenshot.
<img width="320" alt="Screenshot 2021-07-07 113546" src="https://user-images.githubusercontent.com/32511867/124719221-fa35be00-df17-11eb-83cf-be1443795660.png">

**Comment by thomas694** [comment]
Well, then we found another related problem that occurred here.
Maybe with your help we can find the one which occurs at yours. Can you start with a new log file and after the first unremoved blogs are visible email it to me?

**Comment by thomas694** [comment]
Does this still occur in the newest version?
