### ISSUE TITLE
Error 7

### ISSUE THREAD

**Issue by johnflint1985** [TumblThreeApp/TumblThree#519]
First time I see this and now it is in every blog I am trying to download 
![ERROR 4532](https://github.com/TumblThreeApp/TumblThree/assets/29380159/26086259-da68-4fcd-8b4a-b76a57338490)

Most of the pictures are not downloaded anymore because of this. Is it only me or everyone?
Please help

**Comment by joaobarros** [comment]
I can confirm the issue, almost 100% of the photos are not downloaded:

Error 1: Image size couldn't be retrieved for a post

Internal error description
Error reading JObject from JsonReader.Path ",line 0, position0.

**Comment by johnflint1985** [comment]
> I can confirm the issue, almost 100% of the photos are not downloaded:
> 
> Error 1: Image size couldn't be retrieved for a post
> 
> Internal error description Error reading JObject from JsonReader.Path ",line 0, position0.

Just a follow up - on TumbleThree it is an Error 7, just to be exact. )))

**Comment by thomas694** [comment]
These numbers aren't that important. The number just tells you how many errors are currently shown in your error bar.
You can click and remove them one by one, or all at once with Ctrl+Click on the cross.

We'll look at the error in the next days.

**Comment by thomas694** [comment]
fixed in new version

**Comment by Huntpen** [comment]
Thanks!

**Comment by gwh199** [comment]
The error is back as of about March 9th of this year.   Any ideas?
